steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'BfBcatalouge'
  - '--image'
  - 'gcr.io/$PROJECT_ID/streamlit-app'
  - '--platform'
  - 'managed'
  - '--region'
  - 'us-west1'
  - '--allow-unauthenticated'
