# -*- coding: utf-8 -*-
"""streamlit24.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jFjPBnQdkRWqtrNjelXxErTK1JaxmzjL
"""

! pip install streamlit -q

!wget -q -O - ipv4.icanhazip.com

! streamlit run main.py & npx localtunnel --port 8501

